# Generated by Django 3.1.3 on 2021-01-16 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0004_auto_20210113_1618'),
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portion_hall', to='hall.hall')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portion_slot', to='slot.slot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='portion',
            constraint=models.UniqueConstraint(fields=('hall', 'slot'), name='hall-portion'),
        ),
    ]
