# Generated by Django 3.1.3 on 2021-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portion',
            name='hall-portion',
        ),
        migrations.AddField(
            model_name='portion',
            name='spot',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], default=0),
        ),
        migrations.AddConstraint(
            model_name='portion',
            constraint=models.UniqueConstraint(fields=('hall', 'slot', 'spot'), name='hall-portion'),
        ),
    ]
