# Generated by Django 3.1.3 on 2021-01-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portion', '0002_auto_20210116_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='portion',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
