# Generated by Django 3.1.3 on 2021-01-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portion', '0003_portion_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portion',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
