# Generated by Django 3.1.3 on 2021-01-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portion', '0004_auto_20210116_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portion',
            name='available',
        ),
    ]
