# Generated by Django 3.1.3 on 2021-01-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portion', '0005_remove_portion_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='portion',
            name='wedding_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
