# Generated by Django 3.1.3 on 2021-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portion', '0006_portion_wedding_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portion',
            name='hall-portion',
        ),
        migrations.AddConstraint(
            model_name='portion',
            constraint=models.UniqueConstraint(fields=('hall', 'slot', 'spot', 'wedding_count'), name='hall-portion'),
        ),
    ]
