# Generated by Django 3.1.3 on 2021-01-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portion', '0007_auto_20210118_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portion',
            name='wedding_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
