# Generated by Django 3.1.3 on 2020-12-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('available', models.BooleanField(default=True)),
                ('day', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('halls', models.ManyToManyField(blank=True, related_name='slots', to='hall.Hall')),
            ],
        ),
    ]
