# Generated by Django 3.1.3 on 2021-01-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('available', models.BooleanField(default=True)),
                ('day', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('halls', models.ManyToManyField(blank=True, related_name='slots', to='hall.Hall')),
            ],
        ),
    ]
