# Generated by Django 3.1.3 on 2021-02-02 18:19

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.PositiveSmallIntegerField(choices=[(1, 'Wedding'), (2, 'Preaching'), (3, 'Circumcision'), (4, 'Other'), (5, 'Wedding2')], default=1)),
                ('name1', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('name2', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.TextField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('expired', models.BooleanField(default=False)),
                ('portion', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None), size=None)),
                ('wedding_count', models.PositiveSmallIntegerField(default=1)),
                ('duration', models.PositiveIntegerField(default=5)),
                ('duration_end', models.DateTimeField(default=datetime.datetime.now)),
                ('payment_done', models.BooleanField(default=False)),
                ('code', models.IntegerField(default=11111111)),
                ('count_of_visit', models.IntegerField(default=0)),
                ('num_of_unpaid', models.IntegerField(default=0)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall', to='hall.hall')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservation.reservation')),
            ],
        ),
    ]
