# Generated by Django 3.1.3 on 2021-01-07 19:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.PositiveSmallIntegerField(choices=[(1, 'Wedding'), (2, 'Preaching'), (3, 'Circumcision'), (4, 'Other')], default=1)),
                ('name1', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('name2', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.TextField(max_length=10)),
                ('date', models.DateTimeField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall', to='hall.hall')),
            ],
        ),
    ]
