# Generated by Django 3.1.3 on 2021-01-04 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0021_auto_20210103_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Close'), (3, 'Both')], default=1)),
                ('phone', models.TextField(max_length=10)),
                ('date', models.DateField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall', to='hall.hall')),
            ],
        ),
    ]
