# Generated by Django 3.1.3 on 2021-02-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
