# Generated by Django 3.1.3 on 2021-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
