# Generated by Django 3.1.3 on 2021-01-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationimage',
            name='name',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
