# Generated by Django 3.1.3 on 2021-01-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wedding'), (2, 'Preaching'), (3, 'Circumcision'), (4, 'Other')], default=1),
        ),
    ]
