# Generated by Django 3.1.3 on 2021-01-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210104_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name1',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name2',
            field=models.TextField(blank=True, default='', max_length=50, null=True),
        ),
    ]
