# Generated by Django 3.1.3 on 2021-01-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20210109_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationimage',
            name='name',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
