# Generated by Django 3.1.3 on 2021-01-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20210109_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservation.reservation')),
            ],
        ),
        migrations.DeleteModel(
            name='ReservationImage',
        ),
    ]
