# Generated by Django 3.1.3 on 2021-01-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20210109_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservationImages',
            new_name='ReservationImage',
        ),
    ]
