# Generated by Django 3.1.3 on 2021-01-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20210109_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationimage',
            name='name',
            field=models.SlugField(),
        ),
    ]
