# Generated by Django 3.1.3 on 2021-01-17 14:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20210109_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='portion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=24),
        ),
    ]
