# Generated by Django 3.1.3 on 2021-01-17 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_reservation_portion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='portion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=[], size=24),
        ),
    ]
