# Generated by Django 3.1.3 on 2021-01-18 10:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_auto_20210117_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='portion',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
