# Generated by Django 3.1.3 on 2021-01-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_auto_20210118_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='sub_portion',
            new_name='wedding_count',
        ),
    ]
