# Generated by Django 3.1.3 on 2021-01-18 14:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_auto_20210118_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='portion',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None), size=None),
        ),
    ]
