# Generated by Django 3.1.3 on 2021-01-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_auto_20210118_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='passcode',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
