# Generated by Django 3.1.3 on 2021-01-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_reservation_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='service_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wedding'), (2, 'Preaching'), (3, 'Circumcision'), (4, 'Other'), (5, 'Wedding2')], default=1),
        ),
    ]
