# Generated by Django 3.1.3 on 2021-01-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_auto_20210127_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='passcode',
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
