# Generated by Django 3.1.3 on 2021-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_auto_20210128_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
