# Generated by Django 3.1.3 on 2021-01-28 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_reservation_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
