# Generated by Django 3.1.3 on 2021-01-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0020_auto_20210128_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
