# Generated by Django 3.1.3 on 2021-01-28 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0022_auto_20210128_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
