# Generated by Django 3.1.3 on 2021-01-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0023_auto_20210128_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.IntegerField(default=11111111),
        ),
    ]
