# Generated by Django 3.1.3 on 2021-01-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0024_reservation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='count_of_visit',
            field=models.IntegerField(default=0),
        ),
    ]
