# Generated by Django 3.1.3 on 2021-01-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0025_reservation_count_of_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_of_unpaid',
            field=models.IntegerField(default=0),
        ),
    ]
