# Generated by Django 3.1.6 on 2021-02-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0026_reservation_num_of_unpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
