# Generated by Django 3.1.3 on 2021-01-09 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hall.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name2', models.TextField()),
                ('city_name', models.TextField()),
                ('website', models.TextField(blank=True, default='')),
                ('phone', models.TextField(blank=True, default='', null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('district', models.CharField(default='Besiktas', max_length=30)),
                ('address', models.TextField(default='No Address')),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('open_capacity', models.IntegerField()),
                ('close_capacity', models.IntegerField()),
                ('child_park_type', models.PositiveSmallIntegerField(choices=[(1, 'Vale Available'), (2, 'Not Available')], default=1)),
                ('serve_type', models.PositiveSmallIntegerField(choices=[(1, 'With Food'), (2, 'Without Food'), (3, 'Both ')], default=1)),
                ('beverage_type', models.PositiveSmallIntegerField(choices=[(1, 'Alcohol Allowed'), (2, 'Not Allowed')], default=1)),
                ('air_type', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Close'), (3, 'Both')], default=1)),
                ('occurrence_type', models.PositiveSmallIntegerField(choices=[(1, 'More Than One Wedding At The Same Time'), (2, 'Just One Wedding')], default=1)),
                ('live_music_type', models.PositiveSmallIntegerField(choices=[(1, 'Live Music Available'), (2, 'Not Available')], default=1)),
                ('photograpy_type', models.PositiveSmallIntegerField(choices=[(1, '3th Parthy Photograpy Allowed'), (2, 'Not Allowed')], default=1)),
                ('parking_type', models.PositiveSmallIntegerField(choices=[(1, 'Park Available'), (2, 'Not Available')], default=1)),
                ('vale_type', models.PositiveSmallIntegerField(choices=[(1, 'Vale Available'), (2, 'Not Available')], default=1)),
                ('opening_time', models.CharField(default='00:00', max_length=10)),
                ('closing_time', models.CharField(default='00:00', max_length=10)),
                ('wheelchair_type', models.PositiveSmallIntegerField(choices=[(1, 'Wheelchair Entrance Available'), (2, 'Not Available')], default=1)),
                ('praying_type', models.PositiveSmallIntegerField(choices=[(1, 'Praying Available'), (2, 'Not Available')], default=1)),
                ('service_type1', models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0)),
                ('service_type2', models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0)),
                ('service_type3', models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0)),
                ('service_type4', models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0)),
                ('service_type5', models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0)),
                ('service_type6', models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0)),
                ('profile_choice', models.SmallIntegerField(default=0)),
                ('photo_number', models.SmallIntegerField(default=0)),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='city.city')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=hall.models.upload_path_handler)),
                ('name', models.CharField(default='', max_length=30)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hall.hall')),
            ],
        ),
    ]
