# Generated by Django 3.1.3 on 2020-12-22 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hall.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('website', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('district', models.CharField(default='Besiktas', max_length=30)),
                ('address', models.TextField(default='No Address')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('open_capacity', models.IntegerField()),
                ('close_capacity', models.IntegerField()),
                ('child_park_type', models.PositiveSmallIntegerField(choices=[(1, 'Vale Available'), (2, 'Not Available')], default=1)),
                ('serve_type', models.PositiveSmallIntegerField(choices=[(1, 'With Food'), (2, 'Without Food'), (3, 'Both ')], default=1)),
                ('beverage_type', models.PositiveSmallIntegerField(choices=[(1, 'Alcohol Allowed'), (2, 'Not Allowed')], default=1)),
                ('air_type', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Close'), (3, 'Both')], default=1)),
                ('occurrence_type', models.PositiveSmallIntegerField(choices=[(1, 'Just One Wedding'), (2, 'More Than One Wedding At The Same Time')], default=1)),
                ('live_music_type', models.PositiveSmallIntegerField(choices=[(1, 'Live Music Available'), (2, 'Not Available')], default=1)),
                ('photograpy_type', models.PositiveSmallIntegerField(choices=[(1, '3th Parthy Photograpy Allowed'), (2, 'Not Allowed')], default=1)),
                ('parking_type', models.PositiveSmallIntegerField(choices=[(1, 'Park Available'), (2, 'Not Available')], default=1)),
                ('vale_type', models.PositiveSmallIntegerField(choices=[(1, 'Vale Available'), (2, 'Not Available')], default=1)),
                ('opening_time', models.CharField(default='12:00', max_length=10)),
                ('closing_time', models.CharField(default='23:59', max_length=10)),
                ('service_type1', models.PositiveSmallIntegerField(choices=[(0, 'Service Available'), (1, 'Not Available')], default=0)),
                ('service_type2', models.PositiveSmallIntegerField(choices=[(0, 'Service Available'), (1, 'Not Available')], default=0)),
                ('service_type3', models.PositiveSmallIntegerField(choices=[(0, 'Service Available'), (1, 'Not Available')], default=0)),
                ('service_type4', models.PositiveSmallIntegerField(choices=[(0, 'Service Available'), (1, 'Not Available')], default=0)),
                ('service_type5', models.PositiveSmallIntegerField(choices=[(0, 'Service Available'), (1, 'Not Available')], default=0)),
                ('service_type6', models.PositiveSmallIntegerField(choices=[(0, 'Service Available'), (1, 'Not Available')], default=0)),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='city.city')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=hall.models.upload_path_handler)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hall.hall')),
            ],
        ),
    ]
