# Generated by Django 3.1.3 on 2020-12-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='occurrence_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'More Than One Wedding At The Same Time'), (2, 'Just One Wedding')], default=1),
        ),
        migrations.AlterField(
            model_name='hall',
            name='service_type1',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0),
        ),
        migrations.AlterField(
            model_name='hall',
            name='service_type2',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0),
        ),
        migrations.AlterField(
            model_name='hall',
            name='service_type3',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0),
        ),
        migrations.AlterField(
            model_name='hall',
            name='service_type4',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0),
        ),
        migrations.AlterField(
            model_name='hall',
            name='service_type5',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0),
        ),
        migrations.AlterField(
            model_name='hall',
            name='service_type6',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=0),
        ),
    ]
