# Generated by Django 3.1.3 on 2021-01-13 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hall', '0002_auto_20210112_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='user',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to=settings.AUTH_USER_MODEL),
        ),
    ]
