# Generated by Django 3.1.3 on 2020-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_auto_20201223_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallimage',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
