# Generated by Django 3.1.3 on 2020-12-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_hallimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='profile_choice',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
