# Generated by Django 3.1.3 on 2021-01-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_auto_20210113_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallimage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
