# Generated by Django 3.1.3 on 2020-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_hall_profile_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='hall',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hall',
            name='website',
            field=models.TextField(default=''),
        ),
    ]
