# Generated by Django 3.1.3 on 2021-01-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_auto_20210113_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='opening_time',
        ),
    ]
