# Generated by Django 3.1.3 on 2021-01-17 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0005_auto_20210117_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='portion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=24),
        ),
    ]
