# Generated by Django 3.1.3 on 2020-12-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0005_auto_20201229_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='hall',
            name='phone',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hall',
            name='website',
            field=models.TextField(blank=True, default=''),
        ),
    ]
