# Generated by Django 3.1.3 on 2020-12-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0006_auto_20201229_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='phone',
            field=models.BigIntegerField(blank=True, default=''),
        ),
    ]
