# Generated by Django 3.1.3 on 2021-01-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0007_auto_20210117_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='wedding_count',
            field=models.SmallIntegerField(default=1),
        ),
    ]
