# Generated by Django 3.1.3 on 2020-12-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0007_auto_20201229_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='phone',
            field=models.BigIntegerField(blank=True, default='', null=True),
        ),
    ]
