# Generated by Django 3.1.3 on 2020-12-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0008_auto_20201229_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='name2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
