# Generated by Django 3.1.3 on 2021-01-18 10:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0008_hall_wedding_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='portion',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None), size=None),
        ),
    ]
