# Generated by Django 3.1.3 on 2021-01-18 10:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0009_auto_20210118_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='portion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=[], size=24),
        ),
    ]
