# Generated by Django 3.1.3 on 2020-12-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0009_hall_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='city_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
