# Generated by Django 3.1.3 on 2020-12-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0010_hall_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True),
        ),
    ]
