# Generated by Django 3.1.3 on 2021-01-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0010_auto_20210118_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='per_capita',
            field=models.SmallIntegerField(default=0),
        ),
    ]
