# Generated by Django 3.1.3 on 2020-12-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0011_auto_20201230_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
