# Generated by Django 3.1.3 on 2021-01-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0011_hall_per_capita'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='num_of_messages',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hall',
            name='quota_of_messages',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
