# Generated by Django 3.1.3 on 2021-01-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0012_auto_20210122_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='num_of_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hall',
            name='quota_of_messages',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
