# Generated by Django 3.1.3 on 2021-01-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0012_auto_20201230_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='profile_choice',
            field=models.SmallIntegerField(default=0),
        ),
    ]
