# Generated by Django 3.1.3 on 2021-01-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0013_auto_20210102_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='photo_number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
