# Generated by Django 3.1.3 on 2021-01-02 20:17

from django.db import migrations
import django_resized.forms
import hall.models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0014_hall_photo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 300], upload_to=hall.models.upload_path_handler),
        ),
    ]
