# Generated by Django 3.1.3 on 2021-01-02 20:24

from django.db import migrations, models
import hall.models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0016_auto_20210102_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=hall.models.upload_path_handler),
        ),
    ]
