# Generated by Django 3.1.3 on 2021-01-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0017_auto_20210102_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='drone_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=1),
        ),
        migrations.AddField(
            model_name='hall',
            name='praying_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=1),
        ),
        migrations.AddField(
            model_name='hall',
            name='wheelchair_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Service Available')], default=1),
        ),
        migrations.AlterField(
            model_name='hall',
            name='closing_time',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='hall',
            name='opening_time',
            field=models.CharField(default='00:00', max_length=10),
        ),
    ]
