# Generated by Django 3.1.3 on 2021-01-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0019_auto_20210103_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='praying_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Praying Available'), (2, 'Not Available')], default=1),
        ),
        migrations.AlterField(
            model_name='hall',
            name='wheelchair_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wheelchair Entrance Available'), (2, 'Not Available')], default=1),
        ),
    ]
