# Generated by Django 3.1.3 on 2021-01-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0020_auto_20210103_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='phone',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
