# Generated by Django 3.1.3 on 2021-01-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0021_auto_20210103_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together={('lat', 'lng', 'address', 'phone')},
        ),
    ]
