# Generated by Django 3.1.3 on 2021-01-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0022_auto_20210104_2057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together=set(),
        ),
    ]
